version: '3.8'

services:
  frontend:
    build: ./front
    ports:
      - "8080:8080"
    networks:
      - app-network

  backend:
    build: ./back
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todoapp
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:

